force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job_Application</label>
    <nameField>
        <label>Job_Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applied_Date__c.field-meta.xml
<CustomField>
    <fullName>Applied_Date__c</fullName>
    <label>Applied_Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up__c</fullName>
    <label>Follow_Up</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler {
    public static void handleBeforeInsert(List<Job_Application__c> newJobs) {

        for(Job_Application__c job : newJobs){
        if(job.Follow_Up__c == null) {
            job.Follow_Up__c = job.Applied_Date__c + 7;
        }
    }

    }

    public static void handleAfterInsert(List<Job_Application__c> newJobs) {

            List<Task> TaskList = new List<Task>();
            for(Job_Application__c job : newJobs){
            Task t = new Task();
            t.Subject = 'Follow Up with HR';
            t.WhatId = job.Id;
            TaskList.add(t);
        }

        insert TaskList;

    }
}