force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job_Application</label>
    <nameField>
        <label>Job_Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applied_Date__c.field-meta.xml
<CustomField>
    <fullName>Applied_Date__c</fullName>
    <label>Applied_Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company_Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up__c</fullName>
    <label>Follow_Up</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
@isTest
public class JobApplicationTriggerHandlerTest {

    @isTest
    static void testBeforeInsert() {
        //ARRANGE
        Job_Application__c job = new Job_Application__c();
        job.Name = 'Test Application';
        job.Company_Name__c = 'Google';
        job.Role__c = 'Salesforce Developer';
        job.Status__c = 'Applied';
        job.Applied_Date__c = Date.today();

        //ACT
        Test.startTest();
        insert job;
        Test.stopTest();

        //ASSERT
        Job_Application__c result = [
            SELECT Applied_Date__c, Follow_Up__c
            FROM Job_Application__c
            WHERE Id = :job.Id
        ]; 

        System.assertEquals(
            Date.today() + 7,
            result.Follow_Up__c,
            'Follow Up should be Applied Date plus 7 days'
        );
    }

    @isTest
    static void testAfterInsert() {
        //ARRANGE
        Job_Application__c job = new Job_Application__c();
        job.Name = 'Test Application 2';
        job.Company_Name__c = 'Microsoft';
        job.Role__c = 'Developer';
        job.Status__c = 'Applied';
        job.Applied_Date__c = Date.today();
        //ACT
        Test.startTest();
        insert job;
        Test.stopTest();
        //ASSERT
        List<Task> tasks = [
            SELECT Subject, WhatId
            FROM Task
            WHERE WhatId = :job.Id
        ];
        System.assertEquals(1, tasks.size(), 'One task should be created');
        System.assertEquals('Follow Up with HR', tasks[0].Subject, 'Subject should match');
    }

}